<?
include_once("function_cbc_pertanyaan_jawaban.php");
include_once("config.php");

$data = cbc_pertanyaan_jawaban_view_all();
echo "<pre>";
print_r($data);
echo "</pre>";

$VAR_ID_PERTANYAAN_JAWABAN=NULL;
$VAR_ID_PERTANYAAN=5;
$VAR_JAWABAN='JAWABANNYA DISINI';
$VAR_JAWABAN_POINT='10';
$VAR_URUTAN_KE='3';
$VAR_KETERANGAN='KETERANGAN';
$VAR_INFORMASI_01='1';
$VAR_INFORMASI_02='2';
$VAR_INFORMASI_03='3';
$VAR_INFORMASI_04='4';
$VAR_INFORMASI_05='5';
$VAR_INFORMASI_06='6';
$VAR_INFORMASI_07='7';
$VAR_INFORMASI_08='8';
$VAR_INFORMASI_09='9';
$VAR_INFORMASI_10='10';

cbc_pertanyaan_jawaban_insert(
		$VAR_ID_PERTANYAAN_JAWABAN,
		$VAR_ID_PERTANYAAN,
		$VAR_JAWABAN,
		$VAR_JAWABAN_POINT,
		$VAR_URUTAN_KE,
		$VAR_KETERANGAN,
		$VAR_INFORMASI_01,
		$VAR_INFORMASI_02,
		$VAR_INFORMASI_03,
		$VAR_INFORMASI_04,
		$VAR_INFORMASI_05,
		$VAR_INFORMASI_06,
		$VAR_INFORMASI_07,
		$VAR_INFORMASI_08,
		$VAR_INFORMASI_09,
		$VAR_INFORMASI_10
	);


//DEMO INSERT
//cbc_pengguna_insert($VAR_KODE_DISTRIBUSI, $VAR_KODE_UNIT, $VAR_KODE_RAYON, $VAR_NIP, $VAR_EMAIL, $VAR_PASSWORD, $VAR_NAMA, $VAR_JABATAN, $VAR_HAK_AKSES, $VAR_TARGET_CALL, $VAR_INFORMASI_01, $VAR_INFORMASI_02, $VAR_INFORMASI_03, $VAR_INFORMASI_04, $VAR_INFORMASI_05, $VAR_INFORMASI_06, $VAR_INFORMASI_07, $VAR_INFORMASI_08, $VAR_INFORMASI_09, $VAR_INFORMASI_10);


//DEMO DELETE 
$ID_pertanyaan_jawaban=3;
cbc_pertanyaan_jawaban_delete($ID_pertanyaan_jawaban);
 

?>