<?
include_once("function_cbc_callback_jawaban.php");
include_once("config.php");

$data = cbc_callback_jawaban_view_all();

echo "<pre>";
print_r($data);
echo "</pre>";

$VAR_ID_CALLBACK_JAWABAN=NULL;
$VAR_ID_CALLBACK='1';
$VAR_ID_MASTER_CALL='1';
$VAR_KODE_DISTRIBUSI='54';
$VAR_KODE_UNIT='54110';
$VAR_KODE_RAYON='54123';
$VAR_ID_PENGGGUNA='1';
$VAR_JENIS_MUTASI='1';
$VAR_TANGGAL_CALLBACK='2014-09-20';
$VAR_ID_PERTANYAAN='1';
$VAR_ID_PERTANYAAN_JAWABAN='2';
$VAR_JAWABAN_KETERANGAN='3';
$VAR_JAWABAN_NILAI_POINT='4';
$VAR_INFORMASI_01='1';
$VAR_INFORMASI_02='1';
$VAR_INFORMASI_03='1';
$VAR_INFORMASI_04='1';
$VAR_INFORMASI_05='1';
$VAR_INFORMASI_06='1';
$VAR_INFORMASI_07='1';
$VAR_INFORMASI_08='1';
$VAR_INFORMASI_09='1';
$VAR_INFORMASI_10='1';   

/*
cbc_callback_jawaban_insert( 
		$VAR_ID_CALLBACK_JAWABAN,
		$VAR_ID_CALLBACK,
		$VAR_ID_MASTER_CALL,
		$VAR_KODE_DISTRIBUSI,
		$VAR_KODE_UNIT,
		$VAR_KODE_RAYON,
		$VAR_ID_PENGGGUNA,
		$VAR_JENIS_MUTASI,
		$VAR_TANGGAL_CALLBACK,
		$VAR_ID_PERTANYAAN,
		$VAR_ID_PERTANYAAN_JAWABAN,
		$VAR_JAWABAN_KETERANGAN,
		$VAR_JAWABAN_NILAI_POINT,
		$VAR_INFORMASI_01,
		$VAR_INFORMASI_02,
		$VAR_INFORMASI_03,
		$VAR_INFORMASI_04,
		$VAR_INFORMASI_05,
		$VAR_INFORMASI_06,
		$VAR_INFORMASI_07,
		$VAR_INFORMASI_08,
		$VAR_INFORMASI_09,
		$VAR_INFORMASI_10
		);
  
  */
 
 


//DEMO DELETE 
$ID_CALLBACK=1;
$hasil_hapus = cbc_callback_jawaban_delete($ID_CALLBACK);
//echo "HAPUS=".$hasil_hapus; 

?>