<?
include_once("function_cbc_master_call.php");
include_once("config.php");

$data = cbc_master_call_view_all();

echo "<pre>";
print_r($data);
echo "</pre>";

$VAR_ID_MASTER_CALL='1';
$VAR_NOAGENDA='123123123';
$VAR_NO_REGISTRASI='4564564456';
$VAR_TGLMOHON='2014-04-20';
$VAR_IDPEL='54123123123';
$VAR_NAMA='KUSTAN SE';
$VAR_ALAMAT='RAWAMANGUN JAKARTA TIMUR';
$VAR_NOTELP_PEMOHON='08768757647';
$VAR_NOTELP_HP_PEMOHON='08785754';
$VAR_ASALMOHON='WEB ONLINE';
$VAR_UPIENTRI='JAKARTA DAN TANGERANG';
$VAR_PETUGASCATAT='8409077Z';
$VAR_TARIF_LAMA='R1T';
$VAR_DAYA_LAMA='1300';
$VAR_TARIF='R2T';
$VAR_DAYA='4400';
$VAR_JENIS_TRANSAKSI='PERUBAHAN DAYA';
$VAR_PAKET_SAR='PREPAID';
$VAR_TOTALBIAYA='5500000';
$VAR_TGLBAYAR='2014-05-11';
$VAR_LAMAMOHON='23';
$VAR_STATUS_PERMOHONAN='PEREMAJAAN';
$VAR_TGL_UPDATE_PERMOHONAN='2014-05-10';
$VAR_TGLPK='2014-05-11';
$VAR_TGLNYALA='2014-05-12';
$VAR_NAMAUPI='DISTRIBUSI JAKARTA DAN TANGERANG';
$VAR_NAMAAP='APJ PONDOK KOPI';
$VAR_NAMAUP='UPJ PONDOK KOPI';
$VAR_UNITTUJUAN='54110';
$VAR_CBC_JENIS_MUTASI='1';
$VAR_CBC_STATUS_CALL='0';
$VAR_CBC_TANGGAL_UPLOAD='2014-09-17';
$VAR_CBC_KODE_DISTRIBUSI='54';
$VAR_CBC_KODE_UNIT='54110';
$VAR_CBC_KODE_RAYON='54110';
$VAR_CBC_ID_FILE_EXCELL='1';
$VAR_INFORMASI_01='1';
$VAR_INFORMASI_02='2';
$VAR_INFORMASI_03='3';
$VAR_INFORMASI_04='4';
$VAR_INFORMASI_05='5';
$VAR_INFORMASI_06='6';
$VAR_INFORMASI_07='7';
$VAR_INFORMASI_08='8';
$VAR_INFORMASI_09='9';
$VAR_INFORMASI_10='10';
$VAR_INFORMASI_11='11';
$VAR_INFORMASI_12='12';
$VAR_INFORMASI_13='13';
$VAR_INFORMASI_14='14';
$VAR_INFORMASI_15='15';
$VAR_INFORMASI_16='16';
$VAR_INFORMASI_17='17';
$VAR_INFORMASI_18='18';
$VAR_INFORMASI_19='19';
$VAR_INFORMASI_20='20';

cbc_master_call_insert(
		$VAR_ID_MASTER_CALL,
		$VAR_NOAGENDA,
		$VAR_NO_REGISTRASI,
		$VAR_TGLMOHON,
		$VAR_IDPEL,
		$VAR_NAMA,
		$VAR_ALAMAT,
		$VAR_NOTELP_PEMOHON,
		$VAR_NOTELP_HP_PEMOHON,
		$VAR_ASALMOHON,
		$VAR_UPIENTRI,
		$VAR_PETUGASCATAT,
		$VAR_TARIF_LAMA,
		$VAR_DAYA_LAMA,
		$VAR_TARIF,
		$VAR_DAYA,
		$VAR_JENIS_TRANSAKSI,
		$VAR_PAKET_SAR,
		$VAR_TOTALBIAYA,
		$VAR_TGLBAYAR,
		$VAR_LAMAMOHON,
		$VAR_STATUS_PERMOHONAN,
		$VAR_TGL_UPDATE_PERMOHONAN,
		$VAR_TGLPK,
		$VAR_TGLNYALA,
		$VAR_NAMAUPI,
		$VAR_NAMAAP,
		$VAR_NAMAUP,
		$VAR_UNITTUJUAN,
		$VAR_CBC_JENIS_MUTASI,
		$VAR_CBC_STATUS_CALL,
		$VAR_CBC_TANGGAL_UPLOAD,
		$VAR_CBC_KODE_DISTRIBUSI,
		$VAR_CBC_KODE_UNIT,
		$VAR_CBC_KODE_RAYON,
		$VAR_CBC_ID_FILE_EXCELL,
		$VAR_INFORMASI_01,
		$VAR_INFORMASI_02,
		$VAR_INFORMASI_03,
		$VAR_INFORMASI_04,
		$VAR_INFORMASI_05,
		$VAR_INFORMASI_06,
		$VAR_INFORMASI_07,
		$VAR_INFORMASI_08,
		$VAR_INFORMASI_09,
		$VAR_INFORMASI_10,
		$VAR_INFORMASI_11,
		$VAR_INFORMASI_12,
		$VAR_INFORMASI_13,
		$VAR_INFORMASI_14,
		$VAR_INFORMASI_15,
		$VAR_INFORMASI_16,
		$VAR_INFORMASI_17,
		$VAR_INFORMASI_18,
		$VAR_INFORMASI_19,
		$VAR_INFORMASI_20
		);


//DEMO DELETE 
$ID_MASTER_CALL=1;
cbc_master_call_delete($ID_MASTER_CALL);
//echo "HAPUS=".$hasil_hapus; 

?>