<?
include_once("function_cbc_pertanyaan.php");
include_once("config.php");

$data = cbc_pertanyaan_view_all();
echo "<pre>";
print_r($data);
echo "</pre>";

$VAR_ID_PERTANYAAN=NULL;
$VAR_PERTANYAAN='PERTANYAANNYA ADALAH ?';
$VAR_PERTANYAAN_POINT='2';
$VAR_URUTAN_KE='3';
$VAR_KETERANGAN='KETERANGAN';
$VAR_INFORMASI_01='1';
$VAR_INFORMASI_02='2';
$VAR_INFORMASI_03='3';
$VAR_INFORMASI_04='4';
$VAR_INFORMASI_05='5';
$VAR_INFORMASI_06='6';
$VAR_INFORMASI_07='7';
$VAR_INFORMASI_08='8';
$VAR_INFORMASI_09='9';
$VAR_INFORMASI_10='10';

cbc_pertanyaan_insert(
		$VAR_ID_PERTANYAAN,
		$VAR_PERTANYAAN,
		$VAR_PERTANYAAN_POINT,
		$VAR_URUTAN_KE,
		$VAR_KETERANGAN,
		$VAR_INFORMASI_01,
		$VAR_INFORMASI_02,
		$VAR_INFORMASI_03,
		$VAR_INFORMASI_04,
		$VAR_INFORMASI_05,
		$VAR_INFORMASI_06,
		$VAR_INFORMASI_07,
		$VAR_INFORMASI_08,
		$VAR_INFORMASI_09,
		$VAR_INFORMASI_10
	);



//DEMO INSERT
//cbc_pengguna_insert($VAR_KODE_DISTRIBUSI, $VAR_KODE_UNIT, $VAR_KODE_RAYON, $VAR_NIP, $VAR_EMAIL, $VAR_PASSWORD, $VAR_NAMA, $VAR_JABATAN, $VAR_HAK_AKSES, $VAR_TARGET_CALL, $VAR_INFORMASI_01, $VAR_INFORMASI_02, $VAR_INFORMASI_03, $VAR_INFORMASI_04, $VAR_INFORMASI_05, $VAR_INFORMASI_06, $VAR_INFORMASI_07, $VAR_INFORMASI_08, $VAR_INFORMASI_09, $VAR_INFORMASI_10);


//DEMO DELETE 
$ID_PERTANYAAN=1;
cbc_pertanyaan_delete($ID_PERTANYAAN)
 

?>