<?
include_once("function_cbc_file_excell.php");
include_once("config.php");

$data = cbc_file_excell_view_all();

echo "<pre>";
print_r($data);
echo "</pre>";

$VAR_ID_FILE_EXCELL=NULL;
$VAR_ID_PENGGGUNA='1';
$VAR_KODE_DISTRIBUSI='54';
$VAR_KODE_UNIT='54110';
$VAR_KODE_RAYON='54123';
$VAR_NAMA_FILE_ASLI='FILE_ASLI.XLSX';
$VAR_NAMA_FILE_RENAME='FILE_RENAME.XLSX';
$VAR_UKURAN='100';
$VAR_TANGGAL_UPLOAD='2014-09-20';
$VAR_INFORMASI_01='1';
$VAR_INFORMASI_02='1';
$VAR_INFORMASI_03='1';
$VAR_INFORMASI_04='1';
$VAR_INFORMASI_05='1';
$VAR_INFORMASI_06='1';
$VAR_INFORMASI_07='1';
$VAR_INFORMASI_08='1';
$VAR_INFORMASI_09='1';
$VAR_INFORMASI_10='1';

cbc_file_excell_insert(
		$VAR_ID_FILE_EXCELL,
		$VAR_ID_PENGGGUNA,
		$VAR_KODE_DISTRIBUSI,
		$VAR_KODE_UNIT,
		$VAR_KODE_RAYON,
		$VAR_NAMA_FILE_ASLI,
		$VAR_NAMA_FILE_RENAME,
		$VAR_UKURAN,
		$VAR_TANGGAL_UPLOAD,
		$VAR_INFORMASI_01,
		$VAR_INFORMASI_02,
		$VAR_INFORMASI_03,
		$VAR_INFORMASI_04,
		$VAR_INFORMASI_05,
		$VAR_INFORMASI_06,
		$VAR_INFORMASI_07,
		$VAR_INFORMASI_08,
		$VAR_INFORMASI_09,
		$VAR_INFORMASI_10
		); 
 


//DEMO DELETE 
$VAR_ID_FILE_EXCELL=1;
cbc_file_excell_delete($VAR_ID_FILE_EXCELL);
//echo "HAPUS=".$hasil_hapus; 

?>